### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ghost** [jcoyne/connect-program-import#1]
Hey there,
Matt asked if I could have a look over your code, so here we go :)

1. Important one: run `go fmt` on your code -- this makes all Go code follow the same codestyle, which is amazing because it a) kills off any codestyle discussions, and b) reduces mental overhead reading other people's code. Go code simply always looks the same. Many editors can be configured to do this automatically when saving the file (mine is Sublime Text and it does).
2. Another important one: return errors instead of aborting within functions -- bubbling up errors helps with reasoning about control flow. This program is tiny so it's fine, but just 100 more lines and it's gonna get messy.
3. You can turn the big `Printf` call in `NewIssue` into a `Talk.String()` func instead -- `String()` is generally the convention for making a string representation of a struct. You can then just call `fmt.Printf("%s\n", talk)`.
4. Your use of `fmt` and `log` is inconsistent -- decide for one :)
5. Struct initialization -- you can `ImportTable()` simpler:
```go
    talk := &Talk{
        title: row.Find("td:nth-child(1)").Text()
        audience: row.Find("td:nth-child(2)").Text()
        format: row.Find("td:nth-child(3)").Text()
        suggestedBy: row.Find("td:nth-child(4)").Text()
        presenter: row.Find("td:nth-child(5)").Text()
    }
```
6. Installing dependencies -- `go get -d` gets all dependencies, which is simpler than go-get'ing each separately

**Comment by jcoyne** [comment]
@lgierth thanks for reviewing for me. I don't have any colleagues who are familiar with go, so this is a huge help!
